### ISSUE TITLE
Numbering rules issue when adding a connector

### ISSUE THREAD

**Issue by eggplant0-0** [qinscode/2024-CITS5206-IT-Capstone-Group-1#29]
Test Case: Adding connector and downloading PDF. 
The output file does not follow the original numbering style, as the number appears to have been skipped.

![image](https://github.com/user-attachments/assets/82f1474b-bc86-4e39-b330-8202c1dbc1c3)

**Comment by qinscode** [comment]
This has been fixed in the latest commit.
