### ISSUE TITLE
Client Requirements and Feedbacks Summary

### ISSUE THREAD

**Issue by Ellacancode** [qinscode/2024-CITS5206-IT-Capstone-Group-1#6]
**Initial Requirments:**
The project seeks to develop an intuitive interface for managing course rules across various university courses. It will integrate both standard and custom criteria, ensuring adherence to the university's governance requirements for formatting and documentation.
The system will feature an optimized data structure and user interface to ensure data consistency for downstream processes like admissions. This will streamline administrative tasks, and enhance the user and student experience by ensuring the integrity of the data that flows through to admissions.
 
Deliverables:
Centralized Management Platform: A web application to manage and update course rules.
User Interface: Interactive forms for rule entry and management, adaptable based on curriculum type.
Database: Optimized data store for efficient rule storage, retrieval, and updates.
Documentation and PDF Generation: Tools for generating formatted PDFs for selected courses.
User manuals and documentation for system use and management.
Access to the source code and comprehensive instructions for implementation.
 
Key Objectives:
Ensure data consistency across admissions and other rules.
Provide a user-friendly interface for rule management.
Standardize rules across different courses and curriculum types.
Automate rule generation using predefined parameters to reduce manual input.
 
Technology Stack:
If there are any other specific tools or frameworks that you believe would be advantageous for the project, we are open to you using them.
 
Requirements:
Create an intuitive, efficient, and secure user interface.
Implement an optimized database with version control.
Generate formatted rules for the university's handbook and PDFs for courses.
 
Non-Functional Requirements:
Usability, performance, scalability, security, and compliance with university standards.
 
Additional Details:
As you move forward, it will be important to ensure that the application is secure, scalable, and maintainable.

**Client 4th Meeting**
- Admin Page (for access of editing preset rules)

**Comment by adharsh136** [comment]
#### 4th Client meeting(13-09-2024)
* The version presented on the day met most of the requirements and was asked to be set as the first deliverable version.
* An admin page was requested by the client, where the user (only the admin) would be able to change preset rules (These rules are not changed frequently).
* The preset rules can be displayed by default. On the day of presenting, the preset rules were only displayed with the press of a button.
